FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm && apk add --no-cache netcat-openbsd bash

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

COPY . .

EXPOSE 4128

ENV HOST=0.0.0.0
ENV PORT=4128

CMD ["pnpm", "run", "dev"]
